---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iot-macvlan
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "ens21",
          "mode": "bridge",
          "ipam": {
            "type": "dhcp",
            "gateway": "10.0.30.1"
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
