---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gallery
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      gallery:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          ui:
            image:
              repository: ghcr.io/rwade628/gallery-ui
              tag: latest
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 100Mi
          api:
            image:
              repository: ghcr.io/rwade628/gallery-api
              tag: v2
            env:
              FILE_PATH: "/usr/share/nginx/html"
              DB_PATH: "/db/gallery.db"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 100Mi
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: gallery
        ports:
          http:
            port: 80
          api:
            port: 8081
    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
              - path: /v1
                service:
                  identifier: app
                  port: api
              - path: /v2
                service:
                  identifier: app
                  port: api
    persistence:
      db:
        existingClaim: gallery
      media:
        type: nfs
        server: 10.0.10.3
        path: /mnt/storage/k8s/media
        globalMounts:
          - path: /usr/share/nginx/html/public
