---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pv.yaml
  - ./pvc.yaml
  - ./secret.sops.yaml
  - ./api-deployment.yaml
  - ./api-service.yaml
  - ./nginx-deployment.yaml
  - ./nginx-service.yaml
  - ./ingress.yaml

