---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  # - ./api-deployment.yaml
  # - ./api-service.yaml
  # - ./nginx-deployment.yaml
  # - ./nginx-service.yaml
  # - ./ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
