kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-claim
  namespace: gallery
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: media-volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-claim
  namespace: gallery
spec:
  storageClassName: "openebs-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
