---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: playground
  namespace: flux-system
spec:
  interval: 5m0s
  url: ssh://rwade628@github.com:22/rwade628/playground.git
  secretRef:
    name: ssh-credentials
  ref:
    branch: main
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings
              - kind: Secret
                name: cluster-secrets
              - kind: ConfigMap
                name: cluster-user-settings
                optional: true
              - kind: Secret
                name: cluster-user-secrets
                optional: true
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
