---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: playground
  namespace: flux-system
spec:
  interval: 5m0s
  url: ssh://git@github.com:22/rwade628/playground.git
  secretRef:
    name: ssh-credentials
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: playground
  namespace: flux-system
spec:
  interval: 30m
  path: ./
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: playground
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
