# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: route-pruner-secret
stringData:
  TS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:7UIM+KWqCM7IjlPaVPcqnqY=,iv:GzCqCje9Z6Zz/nm1EDVy5mbp0BXRl/IC/D/J99MZmSI=,tag:TosD2kYlDi3kpZcd1abJmQ==,type:str]
  TS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:CILPXnCTYXPsINCUrJEzzipSIHlmuAZQOaccfibuTcwmOMq7da+zh+/0sOEMwPwBYGIkzIiV2k8JLuJ4s7A2,iv:BT+RahD9DiAWZyH2AwzcxXb3+w6NnqumGS4mR010fic=,tag:CKvypZD0EIL90Mly0blO6g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYkhlVWJ5d25ZVGFGcHE1
        dDdGaDhTelZpNDUyYUtMb0g1Tlc5SjNEZ2xnCi9leGswWE94SXhnWVpsdVppdG5V
        dVBXVW5LRHA0Rkd5MUhMeVgzaERVMWMKLS0tIGFwSUtqWWFzK21nOFVMR2dkZHRF
        SXBOMi95VHJyWmI1U0dab25XbnBjQlkK/dBNH/qOXKGmYgp2+ZP7L6/zf0VeJxGl
        ZvS2u6CrVGhAxPQ5F1p43sQ5e6eHDs2+JKGrl4mgWlSx3ME8w5XU/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T19:09:45Z"
  mac: ENC[AES256_GCM,data:HnAvJ3ynDeOND13xhH0MbHrU0kKlxr/1fHW++tFcvywY0THWSYR3R/cRdjgDGj7c84R3295Cu8LSwJD1C0ppJ/jeE7CRhkNzMDuLvvS9X3Iwk3uA3X7LTOAlrgBEshunot5iyDAe5EQ/NOyPVBkNGKnFmIN323gsoeA1mSDC5WU=,iv:uoJXsavY9AtUpM0Rt6ZgeLf8Wcg5FvFA8ZyuxmBv4Bs=,tag:SvsDGBSB4QJDkyldA3usAw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
