apiVersion: v1
kind: Secret
metadata:
  name: attic-secret
type: Opaque
stringData:
  ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: ENC[AES256_GCM,data:G8Kuy50FP2ctDO0tFmUySRGEKdH+ZSL051YDQ2u4b4crWs4SIsHNqkXzNFpEvbcpIHNuO/oJR/aEPUHn9AJLPk+Jp0lbq7WHgHPfYB4yz6YbyEW6o7lMsA==,iv:A5vkXRK5lPWTjBQsx8PeILOP1gYT1Swgt0AiXoRyDsY=,tag:2Y7DY1blol9Ji5xtfvGkhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOWtGS1QrakVpdHl0NEtX
        NFAzTUFhNWc4NjhXdk0vRUJQS3I1am1pOVFFCjlocG04cXRtbjFWUG5sYmpNOHN0
        Tm5DZ24vSmM3SUE1dHJhMzhXemR5bk0KLS0tIDM3TnBzWC82OFllbW9pQk9KdWF1
        MnIrUE96akRrMDMyZjcrLzB4SGZlNUEKF8vTnDo+/ezCihzQ+hM8trcCpLUUZoHj
        94tXMxF+ZNq8JczaCh/cFBO4Ii6DvkCTsFOmTvpERjIGJHeuYk8vug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-12T01:09:57Z"
  mac: ENC[AES256_GCM,data:ZSNSip/wYepLV3dFWQy5c6dn8hQzIxLBt8XncRrltpOQ/C3HKJZiAqACHgqgZdX0xC5m+N5YPw5vIBVq88HgSfS7iND0BdK6Bt9+DoM/PpeOYF075M3CF5ztqwtDfI7xl0cqk51i5+zi3VBskUGLdwI2aYdxTdzIDmKHVP4LnpA=,iv:ZMkpimMua+t8V1acq4oZFBzWq7ASWdvekDyBkT+jHjo=,tag:66uXzQgTW+HrKqvy2QC0DQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
