apiVersion: v1
kind: Secret
metadata:
  name: attic-secret
type: Opaque
stringData:
  ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: ENC[AES256_GCM,data:zSVCq4IkEGaNq1/ICTpVSKrsDQKW7aargKxEvrt0P0qx0O6i7lxTbIdoZA3U2EmAsPDU+3u6okQUWi6RAAp9hPMKf+F3/k6UIlGx5hJzmiWiqiwE1FvOAQ==,iv:4ICUTDwucl/dHVbkCV6TozuD84pVIPKho9oioN39O5I=,tag:BgDTVt/pWyQXFVJNFU0hyg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc0hJWFU3WWFqOHBPZUhz
        NEgxMThCZXd6czl0by9SdUdCQWNjeUlZdkdFCldmdzhubi94d1l6SHhWQ1k2M09y
        dUp0ODJ5VUNIYlFtTDl0Q2F0QXdWaWsKLS0tIFVuamtnN3hxNVJBc3VWRTVlVmI4
        aVF1S0RkTDRBNkR6dTljTEN2T2I0S1UKFx95FY/W4EnC0yINy0hGLDVn8zML1J7N
        xQkSSz1VNZd8KfUqHSNFxTPZSD3fw37gwSc32Ub5HayqvLKOEf0sMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T20:29:44Z"
  mac: ENC[AES256_GCM,data:86KMHsguFT/kscJ1OJJZapMS+FGgyVzw7F5i2gBQ7B6YMG8vyooSRhzt/uwgkryFIQxoWRrKOPTEarum0xA7V/PSc3Z+kcVkq5jZmkUdXay3w0EZi+k7sfuy2YWxnc/T9CzV9BwSqfRXOdoi5mKCIVcFCvD9zwRh2qsvsxCPud4=,iv:GY+N7kuimObRRyl6XVkcmk0LyKMF1nch9iKdG0HRWxw=,tag:f9muYaw4WRSOXUCdvp3cEg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
