---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-config
  namespace: yarr
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
