---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home-dhcp
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "home-dhcp",
      "plugins": [
        {
          "type": "macvlan",
          "master": "ens18",
          "mode": "bridge",
          "ipam": {
            "type": "dhcp",
            "routes": [
              {"dst": "0.0.0.0/0", "gw": "10.0.10.1"}
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: home-static
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "home-static",
      "plugins": [
        {
          "type": "macvlan",
          "master": "ens18",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "0.0.0.0/0", "gw": "10.0.10.1"}
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
