---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mgmt-bridge
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "mgmt-bridge",
      "plugins": [
        {
          "type": "macvlan",
          "master": "ens19",
          "mode": "bridge",
          "ipam": {
            "type": "dhcp",
            "gateway": "192.168.88.1"
          }
        }
      ]
    }
