---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vpn",
      "plugins": [
        {
          "type": "macvlan",
          "master": "ens20",
          "mode": "bridge",
          "ipam": {
            "type": "static"
            "addresses": [
              {
                "address": "10.0.40.1/24",
                "gateway": "10.0.40.1"
              }
            ],
            "routes": [
              {"dst": "0.0.0.0/0", "gw": "10.0.40.1"}
            ]
          }
        }
      ]
    }
