apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-config
  namespace: nvidia
data:
  version: v1
  flags:
    migStrategy: none
    failOnInitError: true
    nvidiaDriverRoot: "/"
    plugin:
      passDeviceSpecs: false
      deviceListStrategy: "envvar"
      deviceIDStrategy: "uuid"
  timeSlicing:
    resources:
    - name: nvidia.com/gpu
      replicas: 4
