---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia
  namespace: nvidia
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: nvidia
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    runtimeClassName: nvidia
    config:
      map:
        default: |-
          version: v1
          flags:
            migStrategy: none
            failOnInitError: true
            nvidiaDriverRoot: "/"
            plugin:
              passDeviceSpecs: false
              deviceListStrategy: "envvar"
              deviceIDStrategy: "uuid"
          sharing:
            timeSlicing:
              resources:
              - name: nvidia.com/gpu
                replicas: 4
