# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Hw8l31P4OZAcU3dYQIZ4fr1XfFGdZ+OWtUI3cFYwyZeQa1BwymAamA==,iv:7bD26GanUx4O1dAwfP014P9dgWTzSmCQgRrDvPz7zFA=,tag:XbBXj9ufNebXzhyj6+Bh4g==,type:str]
sops:
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaWxaUGhndEFQNkpoMnFa
        L01aRHR6bmhpR0JOeU1hbGhXVkVySmFxY3hVCkcvWlhLcEdkSDN2MmU4SlVjZ1d6
        d05xV3Z3VHZmWjZuOU8vVzlQUXdZN0UKLS0tIHM2alBZR05Zd2ZCSXorOGtLc2NH
        dkY2REdaWGR3VEtjQ2xhWlk5MEF5T3cKv1+FRZB/sxd5wCjXmdE02xt6rDJGK2w9
        +Dojp0Xy7vdFKrVXMvggQz9jHVCjhW76qqzQa65lQt9N8tqLaMtNHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-27T13:50:32Z"
  mac: ENC[AES256_GCM,data:wNQyH2VsqANQRJIsqD8/xzw1/gNdoipJU7tjpSCXvKrqiTiOrWWyhSqGyS6p2rSCe2LqnfbU9VMKVUU7SSs116MOUNaH+f74kTiIiLl0folqRRSCaIINu7j1A9DjaGwZiwP2KJ1gW9NYndogkK3bwIweFPqszYKcq+cptgBZoes=,iv:ZDv5ZjiC4DPCc8EeJptUcz9E/stnuvglJ+8cQH5EL5A=,tag:Cj9+h3xj91swLQxOlRuXEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
