# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9izZf7SGm6JiVMISKNZmp73SlksrwnTDJK6OkfSkeuv7ELm0g1vlUw==,iv:ysTkxRmYqY4FMPsOOanQjzRP/lo0Sq6gFaeWmXz7nZ4=,tag:lNfyH4t4VV8enuCAbRpWvg==,type:str]
sops:
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIblI5cm5uWWk1bGsrd0VF
        Lzl0WnhCbWI2N2NKdWhZZkNDeUVsRDFCc1VrCld4YURGNWswL0pGUXNub29paHgx
        eDQzc1UyT1FEV2pGeitKK2grK1ExWE0KLS0tIHZTeUFNQkJReGU3ZzRtY2NwRi9t
        RU5iYUlXNVdyZlpvdnRWdmYxTzYzQTgKNFRbIpe7aoly8PTS4uTCzkUfjUcmw1gd
        YKIUXYlEiL4nhYo3GztjR+jG3hFSetojUObldaISX5PWhpHJFUa77g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-11T13:17:41Z"
  mac: ENC[AES256_GCM,data:ROMlU48+/4EtbBO21rsHqavKIgDd3M8NZUYmHBpuM2hf+c57yPl85cYtdxYhD4zXvnSgCMqzAd0DvrBN83iL7L9YKlFGYjYVvwMNSOmZXwKKdJZgkF5/HAg8RZz5YAJl3MMCptxKg8BHGZi6c9dlXtfEToSY6HIGEyFsBzuFaqQ=,iv:h00VbwKwpUv48HiL/85B/M5mLyT1Lmhg5F76HZe2hJQ=,tag:4u/pFOWCqp3TohJaCYd0cA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
