apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:k5wpekFLdkIr2y8jaxOFC248aIBhLQ==,iv:SrWO49AqDQJPRDRa2eqeReqs9Rq6vCirWwc1m0VA9/U=,tag:S0y3vpW2TniuqPO+pZozjw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:RVMjrLNjLKvv6c22EpYnYWXt/KYHhBA8vvS+7g==,iv:OrAX7WJ29vlzBNx9o8RnmAG4W+Eh2p7BWCkLo2WKWMA=,tag:SvcZrxOQYOzwzIhE6krX7g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RmhYZnkvZFg5ZFZLWjQy
        a0lyejdDbWljblFkb0M4OHBUSnY3Y2V5UmowCk83ZlRKcjdjSlh4OXRWK1RjN0pt
        Z0dpYkFLRUl5YkJTOU9KTGVYd0xGdW8KLS0tIGpEWklqdHcyREd2N2xqMGlrZThs
        QWU4cmdGZDcrcEozbG1JNHZCNjZPNFEKSgv8CEluvgFitJjS8+xiPxIIIOvqBb2O
        dXSoIoPxjTCQuCnSqms518wCFh3WYO8ddSISHogIZYv5Uyu9+HQDVA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T20:07:44Z"
  mac: ENC[AES256_GCM,data:QDzj26mhLqpCpmxW2Imp1j2bgEjmIon6uDoti5g3YVWlINlwCoY1wgR2IpvAi6MiUzHChOAoWS/OFaisCPmstQRLdh/bNNmGzvr47K+DBFghfm2xurwQaAMezGHbJL1Qaxs/YAtKbJrnVGpDOHceFjekMqTVJpSAh/1Zb/aL/zw=,iv:idV5Ze++XIN1v6ZwF3FfB/xnVxv2XBfhOashFTAEgVQ=,tag:XfJB97oKyxu9Qh0JaqEGUw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
