apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:MqRqP71F6aCFm9zI1wB4/3rPsJ/wrw==,iv:HqfE1v1KQ3hKw7v8lWyAan9h34ClpixNwNiwh5qyeYE=,tag:AnEk534ZgJoGlWCZrxHcQQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:fC0FhmLbmdKEgpYfHDMO+kajdC4yL/dc7V+FTQ==,iv:GOkfUlRdyjbGLsKimEGShTzE7c6NTrYZQVFsv8b9Uvw=,tag:cdidRhDM2NRhpnbSnndcdQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGLzkrMGZMaTdzSU9zREVr
        UE9lTytqSVhKOWtrTjM0LzNKdXNPMm1SSHowCkxZSVZYd2NNcytLZjc5SERYajFQ
        TWJET0VMNXB5N2R6a1lFRFNnTnQyd3MKLS0tIERtalpwbDdXYmFnTFNZQzc0NjBS
        NDVFVmhGcDRKUENNM0NSdjdHeXlRZDgKm0sRtUVilnTdGYJ9++evK9KYz+KVKrUP
        T0yN7DWMUKGokTGy5hhrnINYH3kmy58x0xaST+ft9qhHp+tPtPsaPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T15:33:05Z"
  mac: ENC[AES256_GCM,data:catC9YkngRlVnP2aynoqnDCHqFTZQYPvUN4mEaQUvIST5mfD9eof+nObJDM7LKM3IVO+KxKYyA/35zBEbySPbFy3AkqUBT92CkN8SrkoHd1cpxuEcejxC6QA59ROb99mN45q/MI0UCdd+lx9ZBhxCvayPjjbpGqsTfTM3fRkLes=,iv:ytqaoMS/PAK5HYJGtGvb5PrFWVHuE8rJDphEsPpaR6k=,tag:4ATK92TUwPIjZy+iUDb2ww==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
