apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:zy7f1LznFQk7yp2mRH8xUwqRCIfK6g==,iv:UeDnx+ksGx1kOsBd5bEsMJfKrlZThxYs6IsJlQbIq0M=,tag:7Z14fSPrqtd5/jxjUf7DJw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:5/gP09vPu9GLWsfx7K4S5qRqKjPWGGpIDI8h,iv:4QNPOvyD+E7R/7tyvtd+ZDiQEwLxjxJnxcbWJY8T8WU=,tag:rlbomPfXRa7qP9SL1cKhzg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYUVKc04vNzNjLzJnVnFW
        V2psWFFjckk0ZVR5RS9BbnRpdS95MGZqU0hBClBMdjlHTlE1Skd6ZTNGVXhzZzRa
        bmFrNjRpTGtLQ00ybzYyWTVQbTVmZjQKLS0tIG9OdjlYWjdCb1ZpTVVwNmxOVUFZ
        NnFPQXB3K3ZGa0VNd2RLTGhwREtkakUK7H5/A4t31CbBfrOUb6v2W8lCbkkZJeCt
        n9b17Qm+RAH38DCeN07TNYfkT4U0YZ7D17hTfKrn6/GxZn+Bq1l+0A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T15:24:56Z"
  mac: ENC[AES256_GCM,data:DGJJvMVUoAVlShqZll8jO9kIyJ5uHpuCjqOq//PkkZV9jQLoZQ8VJmtKgzvg+1ZvvNdaPuCAd8fYQmvWc4HuFgii6f2NOS2RdYRQiXqffaecBz10SSIbBwQFjE+WedNVs/daGZ/CNf3keGs8oHd8wQlfYnmoZi922Q1QhSOb7r4=,iv:arUYveuREhdZuDBbv0qROcQv2CWWkRpJWVPiGcWfcN0=,tag:a621k58NnJ1oiTj3cThr0w==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
