---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: epg
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      epg:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/davidclaeysquinones/epg-info
              tag: 1.0.68@sha256:8f946e7df92cd02530d6d8df5eb8f87ffa35ebb7fc091baceda94a83c34d20b2
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: 3000
    # route:
    #   app:
    #     hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
    #     parentRefs:
    #       - name: internal
    #         namespace: kube-system
    #         sectionName: https
    persistence:
      config:
        type: nfs
        server: 10.0.10.3
        path: /mnt/storage/k8s/media/tvheadend
        globalMounts:
          - path: /config
