apiVersion: v1
kind: Secret
metadata:
  name: ghcr
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:W1u4uwKIyUYZLahtpeyFa5M1S56EwpdChX4HmvAcJUzaSSHBaLVh6TJm9M+UY8fun6W+dKCD/iiz3/F+ymcS6u+0u76GGhnlR2BhAYQqgCaHvohKH64kYS8BFD85QCjrlN1uagZY7BGPofq02hw81kYIO0CV0ypxD5FjhK1d8TL2,iv:7cwBP95nLX5MHVJG30PROXIk1LZds2nDRzlwFe0vBbU=,tag:n2ZVehLizcvir492pSfxTQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ1lPV0oxREZzeVk0OWNT
        M2dvNytHMEJOdU41bFEwZXNGTTdCWWlHb3dnCnJZZm5OUXJMUHRVOFpjQzFGcFVV
        TkI5dnFXejhlbUQvZjlaclJsM0M4SGMKLS0tIEpXby9Ua0w0RlRQeWR4UVc1WWR0
        TDAxYWgrVUkySnhMcTdwNkpLNCt3RHcKp1gdWt9K6DlxK5AXdBxPGsELyP9hqUeE
        p8G7XBTAF2WpTrMap6hxZfLMtIy6QiPChHQ8Cx/NFeGJIYez2ghA1g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T13:52:59Z"
  mac: ENC[AES256_GCM,data:DE+nTClrsUsgLWkjdHsA7WjgDTF42YYEGx2k40FioDVVy+C/BfCI40UFBWG4mEUrBUXyhijdh+TwQrJ1R0ILNGaWIsxdXynBH3EZjgDkwyLjtlIjlXIg5Eol8fzKyZfTw/BnaJttrhuvRSabFHRx4sk/vuDW0IG+Q26tJxz+wnk=,iv:gQDWXo8RmWfVitiy/J3wvLXjij3tbk8Wti4QODkAuBU=,tag:a4eCupFGxIeQXeEamNP50w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
