apiVersion: v1
kind: Secret
metadata:
  name: ghcr
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:0sq01eGBKWUP57tOga3Kx0FLz20inWJDLRAeLN+HAq3zXKJhhpvdQLHNAju6Akf029uOV+JqjQnyRVWXs5h9A0v4ZnqglsCSYzXp2MNMctDbnyQym85QYHJyTZqNWsF7V+iMTyPMOhgRSFSSgyLWSDqRDOA10mo5PR2m9kC+i22N34wILQ5djA==,iv:3PS8WXLfU0Xbw0g7Z/KDRCaFJC3PK/nYQU1UOwpP8LI=,tag:Z9leMSKxKQ2bsSi9eOft8A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWXRISWdEWlFHVEZkVU5p
        M1VGOUdGVjVqMzJDdFVIazE5ZklGbDA0dFg4Ci9rTFNKVlJ5QVhkSGxpMWwrTTh3
        RW9XbnNvN2tuemEwaG43U1FSaXk5TzAKLS0tIGxBQ0ZwWW9YNXk2blNKWUZxSDVG
        RHgxRUVLWVV0U3Q1TWNsNVlERThmcnMKESixq3Liqtoxzpi5ctP5fzJsZOZ89wGj
        MjaXH1+6eNgDhclqWya86+cyu2sOIxGV5nXAgcx2g5Q4kokKY6C+Rw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T21:00:16Z"
  mac: ENC[AES256_GCM,data:HZksHKEiDDBbzoUYIUfcpOMfomB+R3HYq/wSZHxqggTYAAeBXP30vpqWcafQbwBWgrvrCa3FJkxvov/YA/Ul14KdMePue9PcKW4YBkCkSL0i+yRV0y6DpZcruApsB9afCx+QgIIgBGaFWiizwF+9Fi65ePK9ISJzAtiXbFAsvlA=,iv:gJfiU7KmICE+BboL5hR7f201+Yy0//9Aj5O9jUF6p10=,tag:/lu6mlfwSoXOiT6lwY+Kww==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
