apiVersion: v1
kind: Secret
metadata:
  name: ghcr
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:ECHLq4cRbnSXH5pNv9HldzMO3bjWI6DzNJu2XbCFiBeJSAiuLDsIA01lZybQ07MDKrDD0E8SPGGS2Bz96cKTzA4gr47fDP7jRpOOOe42YZWYNZEDKLWRyB/Nz6wua8tRzsaV3hVXEUlOge7cut/boQmyVFpqmMHMHMcJefaDwRNlfqBoK45eJe4FlA0wwRwvcqBM8+LOM/vi04Mk4CnrUw==,iv:BoFxYZJPmfVLmP+r2Kvhl8OGvwURwqzMeoHFzxF2HQM=,tag:Y/OmgD4vkOpyr+2vG8160Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRzNiaVhOT2NnTk5YWEFz
        WDRsYjJNU2h5YXE0ZzhvczQwWFlpak9xVldJCnlIaVluM3dlalQ0UlVNb2lOaUcz
        YkMvZ2FwK1hkTDkyeHpFUFF1VEFoY1kKLS0tIFBqVkIzYTFWM0h1KzJBTXlWTE9t
        NTZVWDMvOFNKb1pHK2dBSnNrbzNiVzQK8SKDls95o2zgIke66NPDXdOWEGDUlFla
        4s9w1V5xRQ1smUnswpwYa/ji5QxsoKNOofNfTVLKytRLsxTY4ivzTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T15:06:41Z"
  mac: ENC[AES256_GCM,data:3AQ8ygt4gyv7K6jOwuwsL/zYJ4vQ/kNGM7GRMjF1TKAGF9Zfo0w6/CjJndqy0wcQSTVuqXwomkh5VUh7Gt1ITZ81z4PFB59oWdQX8nkv+MvgNh6mwbNo8/8kMRgm+KYeYuyDar9BfNS6wfwBBMF8/MfafvWog7bSS8KFyV8exbI=,iv:WZJI64P5l2h8rpenoqSMByf7hy0dwwZBlIKDk7Jcbwk=,tag:X+FYnyq2A6LIung3B4sr7A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
