apiVersion: v1
kind: Secret
metadata:
  name: konflate-webhook-token-secret
type: Opaque
stringData:
  KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:NrzCz4ZeWOkmCiCqm1R0pFP5bmvHZpJO,iv:+kQWrKCOHs1bq/UT9K6ph9E+YIwdjFfEzNfCTnnrV9Q=,tag:Sdz2SoPxZBYOKBZRGtNGug==,type:str]
  KONFLATE_APP_CLIENT_ID: ENC[AES256_GCM,data:cEbGX44BeFdR/cYW/4/OiQKjOlY=,iv:YnjZcfVR46FjVy3Cr6MPTs4EcoAXMTijCLU6W4N0tjE=,tag:0OrugsmboSWktdIjwhd7uA==,type:str]
  KONFLATE_APP_CLIENT_SECRET: ENC[AES256_GCM,data:uDprSdlzgaN1ZGHBTCkgRarOmyzrO6JnOIpq/JgEawvO1JqKmVwihA==,iv:joNqIadycfgLZ1xQyXJtV8KYZZSHQUS4nCPHDzt7uuY=,tag:qRfLhob1gZ3KHNERBqIM/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaVdrTzFoQ01nalQyQ2dr
        ZFVrTlhBZWpyWXJyUVhOQlJwaUJJVjd5ZXdFCi9kMEdBb0dxTFZiNjBhVzBzb3p4
        d0VVcnlUajN6T1U5VFYrV21IQ1czWWcKLS0tIEdjd0V1ZnBQalpPdG4xM21Fenpz
        VUZzMkJvamdaSVFCTnQwTDJxL1hJK2cK6OvyrKS3pUW34X+FZUPxBDSNVFYT6HT+
        BuRFC+0XMsaub631sr3MxNrT3BwyLVVTlszGFC0Cvhi1Sd1oWAp3dw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-15T15:49:22Z"
  mac: ENC[AES256_GCM,data:uu1o/tbDXqK2rg2YNiVPyzUeBAwlR4NzAkFwUJKZD/sdaFuZEtiCfKRVOouKpqPx7+MTaqgEhVTPfD0Tl2rcbB6avhiLAMRY7GfjV9HPZom3tk1zSrgxQuNXmretcwPTwXusTfh7Smroux34j2BT1/qJRemUZzHRGcN+k09vGCI=,iv:zqCiqKmS9azy1yctsxcL4XadIXdkpn03NcsUlh/PE1A=,tag:nxA79B3JHu0uRnUMY+5l4Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
