apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:jOXvFLvu6UAMZRbziLQX1Cqk,iv:qm8T+a8flK8KFyuZ4wieb+/AFBpvhm2YbJPMrvXXFaA=,tag:cL3Azi40Z5t4c68cdU4J9Q==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:0lc9JoJXM0eiU4Re61vsSj16,iv:7RSsGNACSTTZSki0LTlEaXsHXrmpcO+CR/qYo+hMqxo=,tag:H98pWJekejsm4OM1vwiNaQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L3QxN0JDY3pFaWthQkhi
        aTVJY0M1YmVHUHl5RVZ5VWFKYVU1bVJxTlE0CkJZNlFHK1c2VXgrbXN0cXFuZmpx
        Vk9HaEhUSVVKZjhHZjJ4eHNuNkdHSm8KLS0tIGtsaHFGVHcrZEZHVk4wcTB6bFhj
        MmJVN3J4Tk1qTm5JLzIyVk1vaUJMUUkKOIjDWMzITEgXNKF5SeXAyiHIpbvv90v8
        UV3A0UAWwzIVdjegPtegoaL1G6wvJ/sPoZx48PQ1OTlltQ1fW6uIhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-15T16:39:29Z"
  mac: ENC[AES256_GCM,data:OnPLuZxv0Ho0sWJDUjj3uCzGHh79oddRzFsEqY3fVQq7i+RzA7LLxHdkMe+S3Eto/D95VWS62g/uxElS/zA7GvOvUtE1FEUNY0Q9EUhvnmqEcSkXjXEJl4rpU+unqFnSdeeaL/xlECBdpO1AsYRFJlxgfbJkIZmAuKCN4lHTpfc=,iv:5dV9WEAbKVSHQ8ZyH+7QIl5qiECeRKuG9Fk7zNXPqLY=,tag:gr51edYs90oOCkOUf2EG1Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
