apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ahI/J0GKlz0yfDpKBzRfQMBJmf/VHE64RPO1kFOU3Pw=,iv:qE/JVnE8eyiA9A7nzvKR6+Dx7MmDspYkfS5TertV6us=,tag:1DQru4SjWkYf58M+Eh6evA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VW02WnBLeDhVMVRmMVpF
            RDVKZkJPclV4TVM5ZmVjOXBFTVU1RWF5Q1JFClhFQjhocWdMNzc5dTZKSUpsYXdv
            aGlwOElNV2xIemQzUWFzaVFxVFBRVDQKLS0tIFJma2dqTTdLVHZJYUhPaXBiYkRq
            YU5IT1BxQjgwT1BPeStLK0xoMzFwSEEKTKdZ8otmmZ1kyxwhPrICO/fyeUmxtPt4
            0zGzeqnWOjOMS8Fq6VKfmiSC0QoVicw9r3ByztE0RbNSjKxvzp7W0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-22T16:10:05Z"
    mac: ENC[AES256_GCM,data:E1L+03WdfOgmuTd/EFiDjpwy5IB8FlZS1fiz1069cb47TsDa5jJqAvrfMQOG7r4m1qLFvZNLqcsXvPU6KKzbRRsN+wAZihl+qTFBB8Mf2NNEI8flsOPI7ueCXMdVa7VV7czlbIjvlTBliKS5yGnWp1LNACFNlFfhNYojHfTmS38=,iv:9Dtbx5yru9sTArObEkQgy0G56x1m/6Nzhl7SGmEj8/w=,tag:6cqWyPo0SOTzVDrLUE8lsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
