---
- id: radarr-striptracks
  execute-command: /config/striptracks.sh
  command-working-directory: /config
  pass-arguments-to-command:
    - source: string
      name: "-l"
    - source: string
      name: "/tmp/striptracks.txt"
  pass-environment-to-command:
    - envname: RADARR__SERVER__URLBASE
      source: string
      name: '{{ getenv "RADARR__SERVER__URLBASE" }}'
    - envname: RADARR__SERVER__PORT
      source: string
      name: '{{ getenv "RADARR__SERVER__PORT" }}'
    - envname: RADARR__SERVER__BINDADDRESS
      source: string
      name: '{{ getenv "RADARR__SERVER__BINDADDRESS" }}'
    - envname: RADARR__AUTH__APIKEY
      source: string
      name: '{{ getenv "RADARR__AUTH__APIKEY" }}'
    - envname: radarr_eventtype
      source: payload
      name: eventType
    - envname: radarr_moviefile_path
      source: payload
      name: movieFile.path
    - envname: radarr_movie_path
      source: payload
      name: movie.folderPath
    - envname: radarr_moviefile_id
      source: payload
      name: movieFile.id
    - envname: radarr_movie_id
      source: payload
      name: movie.id
    - envname: radarr_movie_title
      source: payload
      name: movie.title
    - envname: radarr_movie_year
      source: payload
      name: movie.year
