apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qwen-35b-route
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames: ["qwen.${SECRET_DOMAIN}"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1
      backendRefs:
        - name: qwen-agentworld-35b-service
          port: 8080
      timeouts:
        request: 0s
