---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    # remediation:
    #   strategy: rollback
    #   retries: 3
  values:
    controllers:
      qbittorrent:
        initContainers:
          network: 
            image: 
              repository: nicolaka/netshoot
              tag: v0.13
              pullPolicy: IfNotPresent
            env:
            - name: DEV
              value: eth0
            command:
            - '/bin/bash'
            - '-c'
            - |
              POD_IP=$( ip route | grep $DEV | grep default | tr -s ' ' | cut -d ' ' -f 3) && \
              ip route del default via $POD_IP
              ip route add 10.69.0.0/16 via $POD_IP dev $DEV && \
              ip route add 10.96.0.0/16 via $POD_IP dev $DEV && \
              echo -e "\nip route after fix:" && ip route
            securityContext:
              # runAsNonRoot: false
              # allowPrivilegeEscalation: true
              capabilities:
                add:
                - NET_ADMIN
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent-beta
              tag: 5.0.3@sha256:4b9de3356475bd97fda3fb4d98f213e8d139aef15e7bd20dab72973e661901dd
            env:
              TZ: America/New_York
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 50413
              # CROSS_SEED_ENABLED: false
              # CROSS_SEED_HOST: cross-seed.default.svc.cluster.local
              # CROSS_SEED_PORT: 80
              # CROSS_SEED_SLEEP_INTERVAL: 0
              # PUSHOVER_ENABLED: true
            # envFrom:
            #   - secretRef:
            #       name: qbittorrent-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: default/vpn-macvlan
      securityContext:
        # runAsNonRoot: true
        # runAsUser: 1000
        # runAsGroup: 1000
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: qbittorrent
        type: ClusterIP
        # annotations:
        #   lbipam.cilium.io/ips: 192.168.42.122
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *torrentPort
            protocol: TCP
    ingress:
      app:
        className: internal
        hosts:
          - host: qb.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: qb-config
      tmp:
        type: emptyDir
      # scripts:
      #   type: configMap
      #   name: qbittorrent-scripts
      #   defaultMode: 0775
      #   globalMounts:
      #     - readOnly: true
      media:
        type: nfs
        server: 10.0.10.3
        path: /mnt/storage/k8s/media
        globalMounts:
          - path: /media/Downloads/qbittorrent
            subPath: Downloads/qbittorrent

