kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent
  namespace: yarr
spec:
  storageClassName: "openebs-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qb-config 
  namespace: yarr
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
