---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qb-config
  namespace: yarr
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
