---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  # - ./whisparr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./recyclarr/ks.yaml
  - ./flaresolverr/ks.yaml
