kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: whisparr
  namespace: yarr
spec:
  storageClassName: "openebs-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
