apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:232cNFu79Z1EbpO13id+I0s0ptuxQiSdTKkx+VIN,iv:yptcGt0LKewbsjZ+hK43X/G2kEN7+Affrxxp4ml0mgY=,tag:k6elA7Ek9zgtwSmwzYkvUw==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:r/nXNvfajulsWCtxcMeruSQeyKJekD82KYKinlZz,iv:SLljqOvoltmyKcKi6sh3w27MurtZIkTici6e1ekFrgo=,tag:frY1SPcVh/Zwbl0izJ1VAw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OGQyNTB4UUFBWTlPdW5Q
        Rk5ZOFFFaGZuRjhyWFpXdE5YVzFQNTE0ZUJnCnNPemtwSGNGamNQYm9oU1F5UDJD
        OVZxSzVHUkQ2dkZGZk9hcFVYdVA3NGMKLS0tIGNUOWRnRmZ1TmM1cCtMb0pnTGJr
        L3M4T2ZKNEYvTWdseDhXc1VwTVlVcmMKPtYtWa4a6uOsyowD3e0SeAcNlQAY2P0r
        iuCGIRdDMf1Z9mS/TqoOg+AOfpV5w8x+gbEBkcQLJ1hKFf6Kn/Uopw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T12:53:31Z"
  mac: ENC[AES256_GCM,data:mbBYfyz7kl51nzIXlEZlNeRBtOpZY/3+KZRg7qxcf4wsgnNfIb52MhpUS55K+h7fh2ohycoxe5WlYcXxvbd6bk2SKBsLZR7dJ24mx8f7/89ncoIS0ezn5+RSi0XSUorQMmHFKu+Y3Q9FzFTK5gjqtJUWOMtGGujSAp6qL2k3NGw=,iv:+154CphwmnnE/LFE+H+K3CwoSIPQ9mKANSqMUyl3KVs=,tag:ZrTTrdHsbU1BNSrGCuNJsA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
