---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: ser8b
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  feature.node.kubernetes.io/amd-gpu: "true"
  topology.kubernetes.io/zone: m
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: bond0-m0
selector:
  match: glob("70:70:fc:07:d2:21", mac(link.hardware_addr))
