---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: recyclarr-config 
  namespace: yarr
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
