---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    expose:
      tls:
        # cert is controlled by ingress resource
        certSource: none
      ingress:
        className: internal
        hosts:
          core: harbor.casadewade.com
    externalURL: https://harbor.casadewade.com
    updateStrategy:
      type: Recreate
    existingSecretAdminPassword: harbor-secrets
    existingSecretSecretKey: harbor-secrets
