apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:/4wAw63rrV/6UsVeIWEuuHa8,iv:xmDKkrE8o6VlcrWPoUqYgMlzcgNHmHM5GZi98JmmVeg=,tag:F4Ct9obnOiAMvtyF7Vi4fw==,type:str]
    password: ENC[AES256_GCM,data:5GbPM0xzJVUL77rPPt2Y2y6K,iv:Wava1gf/RFd9mZe/NdELCNRlW1KMCnADvm3VvpzA/Dw=,tag:gZ5HYCJ7WZFPUyCOnEiZ0Q==,type:str]
    secretKey: ENC[AES256_GCM,data:PgL7BN2so5fWRaxU9AaqQg==,iv:yX1tqxE9X1Rot8bqs1up+RyNEuJOY7YfS3rZR3i//C8=,tag:+wRd37rwVVNIL8sJVm4cNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc1l2ak9tS01FREtnaXYy
            cWZYL3NiYmVqSytVOEpMRXZGRlY0Yy80Z0ZRCmZwRS9ER3Zqd1NVM2pwT256bEdr
            THBZNWR1amFOQUVNMmNsQUc1bzcwQlkKLS0tIFdnWUpMWkJDcElHM0ZLTytIL2NQ
            L3ZWaWo0VEU4bkNTMkwyRDYvRHB5cE0K8ziAEO13/RO2MEjZ8Tenk/BB9jzYwlER
            XocAvDa5Q1VJZpcAuqF3VB96ogtVJaZ4S6pASKmfAN/47F5QuTREXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T20:54:50Z"
    mac: ENC[AES256_GCM,data:06DptJpnNqWEPSA8leFh9uNO8/1zZb1fuPCCPO3HTG0enKLkaQUWSu4/N0zHMi9MwGqYEGquDU7nCRTa8y/khjKosEd12JnpqMG8yB7bL+ZkD9RMpJKdv5BPNYPfqy6+zR3Cu22K0c0BEL5xpLmcFqJltnwIadYWLAHSt72drJQ=,iv:WrTi0OHM/1lI8gq7tDF+ePzbfFER6nafpSHoLzxDwN8=,tag:I2cUo0vtR3WVz9XhYqZEVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: harbor-database
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Xq5wpyVlqecqtahgc6nkAQUq,iv:/jCbgSKcisA421F4lJBq+9cnpguxmLQIyHkDZOGxDks=,tag:RQX/lhCZwr7kQetCmYoVKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc1l2ak9tS01FREtnaXYy
            cWZYL3NiYmVqSytVOEpMRXZGRlY0Yy80Z0ZRCmZwRS9ER3Zqd1NVM2pwT256bEdr
            THBZNWR1amFOQUVNMmNsQUc1bzcwQlkKLS0tIFdnWUpMWkJDcElHM0ZLTytIL2NQ
            L3ZWaWo0VEU4bkNTMkwyRDYvRHB5cE0K8ziAEO13/RO2MEjZ8Tenk/BB9jzYwlER
            XocAvDa5Q1VJZpcAuqF3VB96ogtVJaZ4S6pASKmfAN/47F5QuTREXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T20:54:50Z"
    mac: ENC[AES256_GCM,data:06DptJpnNqWEPSA8leFh9uNO8/1zZb1fuPCCPO3HTG0enKLkaQUWSu4/N0zHMi9MwGqYEGquDU7nCRTa8y/khjKosEd12JnpqMG8yB7bL+ZkD9RMpJKdv5BPNYPfqy6+zR3Cu22K0c0BEL5xpLmcFqJltnwIadYWLAHSt72drJQ=,iv:WrTi0OHM/1lI8gq7tDF+ePzbfFER6nafpSHoLzxDwN8=,tag:I2cUo0vtR3WVz9XhYqZEVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
