apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-mcp-secret
stringData:
  HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:u3eGsjFQvbbaSgvcynGOO5GMfkIoIbBnbqhDxuTHdbnhT5gN9mThW3vqwHg+291orl6ZAgJvu+RunB3/sp2z4fELmvqbEIKoYXM+t0KMsah9DEwmyrlEM/288DFF4RW7DQGrp/Rs0Jcgp+gnvN/zvs2GOw9hc3ilSPwLR/lA4GU+msChSJdxzABD919T2HUVH7rQ8Bh0X0mIksJGMZMieNy6FLS5qgCpBz9vxmB2dDQntVs2vcMI,iv:fpFALkCGaQEFTH4lk6+NNTUfDDLkPF3UOo1Z/N8GkW0=,tag:LFQ879tl9dSA+6n6KdaulQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VnV0YnNLbmhQNnlnZ2do
        bkZ0VFV2a0FRaEUxTGI1VmE4b09QZ1QreWp3CnVvaW1tSFcwS0lEaHU1QXVLbzRv
        UXJYRDM3S3pHU001NDV4eWpNV1o4amMKLS0tIEphVjljOU1KMWFTSXZMN0FDdE5I
        RVZZekZKbVZXd0h5Q2ZTTC9YQ01yek0K9w+gqNouTsDxx8gWsSGMbmmjNC/CQq9i
        hHQVDBWl9tO89j8W+NeZnPDV03GWV5farJE4b/8tXz2TvZXcCKgOyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T12:54:41Z"
  mac: ENC[AES256_GCM,data:uUjGxsCrhKzVZp7OcDU1vM5AvQlJmh94VveXJcxZfDBVgLMf/KTsDJvEVuG5FG0YV0QtqzcHLj2nP4ktAcE5fJqkewmMXN9yEnCKa+IzYXpoA2OU9sJ9P6EeHc8x3LHUnTwxz8F6XUYR+YepRjqbFrq4PDdjryGXvDFVP/mse7k=,iv:gP8HaMapKUyU+5cpTD/2/2mzlMNm+oIrYmGxhkkmFvg=,tag:a/38O6jB0bjytAXp/dsouQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
