---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mgmt-bridge
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "mgmtBr",
      "ipam": {
        "type": "host-local",
        "ranges": [[{
          "subnet": "192.168.88.0/24"
        }]],
        "routes": [{ "dst": "0.0.0.0/0", "gw": "192.168.88.1" }]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home-macvlan
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.10.0/24",
        "rangeStart": "10.0.10.200",
        "rangeEnd": "10.0.10.239",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.0.10.1"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vpn-macvlan
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.10.0/24",
        "rangeStart": "10.0.10.240",
        "rangeEnd": "10.0.10.243",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.0.10.1"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iot-macvlan
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.30.0/24",
        "rangeStart": "10.0.30.250",
        "rangeEnd": "10.0.30.254",
        "routes": [
          { "dst": "10.0.30.0/24" }
        ],
        "gateway": "10.0.30.1"
      }
    }'
