apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: deviceconfig
  namespace: amd
spec:
  driver:
    # use talos amd drivers
    enable: false
  devicePlugin:
    devicePluginImage: rocm/k8s-device-plugin:latest
    nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest
  metricsExporter:
     enable: true
     serviceType: "NodePort"
     nodePort: 32500
     image: docker.io/rocm/device-metrics-exporter:v1.2.0
  selector:
    feature.node.kubernetes.io/amd-gpu: "true"
