---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-operator-charts
      version: v1.3.1
      sourceRef:
        kind: HelmRepository
        name: amd-gpu-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    kmm:
      enabled: true
      managerConfig:
        controllerConfigYaml: |-
          healthProbeBindAddress: :8081
          webhookPort: 9443
          leaderElection:
            enabled: true
            resourceID: kmm.sigs.x-k8s.io
          metrics:
            enableAuthnAuthz: false
            bindAddress: 0.0.0.0:8080
            secureServing: false
          worker:
            runAsUser: 0
            seLinuxType: spc_t
            firmwareHostPath: /var/lib/firmware
