---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deviceconfig-metrics-exporter
spec:
  endpoints:
  - interval: 10s
    port: "5000"
  namespaceSelector:
    matchNames:
    - amd
  selector:
    matchSelector:
      app.kubernetes.io/name: deviceconfig-metrics-exporter
