---
apiVersion: v1
kind: Service
metadata:
  name: deviceconfig-metrics-exporter-custom
  labels:
    app.kubernetes.io/name: amd-operator
    daemonset-name: deviceconfig
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: metrics-exporter
    daemonset-name: deviceconfig
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deviceconfig-metrics-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: amd-operator
      daemonset-name: deviceconfig
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kmm-metrics-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kmm
      control-plane: controller
  endpoints:
    - port: https
      path: /metrics
      interval: 15s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
