---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: selkies-claim
  namespace: desktop
spec:
  storageClassName: "local"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: desktop-nfs-volume
  namespace: desktop
spec:
  storageClassName: ""
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.10.3
    path: "/mnt/storage/k8s/media"
  mountOptions:
    - nfsvers=4.2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-claim
  namespace: desktop
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: desktop-nfs-volume

