apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:9MDmnGB8VENdhHPBnNM=,iv:/ro90yQgpI/zHmK28sh7ft1XI4ES2ueU8YouoQ8ONFA=,tag:FnDMTc3y59iBPnYMYsCWUw==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:csQEghvzEBcBzRJyWkEZHBsvdTXL,iv:JrobSrSTKoAbZ3Ym66aOWGLzi3aWkq59JyXWm3HSivg=,tag:SlVO0WceYUrLOybTh9URjQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zYTjK1kTy2by8KK3vZOXcw7lPlmIUZS0DCTzM6zBQ9qWeeUk,iv:c9OX3bg8ABeKZkmuprWoo+Dpjr+98lPergzZyXCO8nE=,tag:WDGeOW0epl9Qh9A4WuU6fA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMGY3QTZnWnZnSk5ZbkhG
        SFBmMWpmcXd4dHF2ZmZWeFhXSWZ2Q1lWY1cwCmk0RHlNdXYyK0tsQ3E4RUNhNVZt
        RHVKK2xqUU9vRkRDdHp6MWhjdHlhaHcKLS0tIG5tbFhqVmFRU21iQk1nZGNnTURU
        SVphSnk5WlRzMlltMnV3bW13cXdmdzQKnDPGdEtRSzIiPthP3xw2zWdfckYL3qsU
        u3blGiju9k+PiZAaVbFCaY4KxmKtndbcC3v7/ZhQAhzVUO96b8Lwlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T13:33:47Z"
  mac: ENC[AES256_GCM,data:bqN8Fc9bDmZwGJ3VAAeiMm0GdGm3j4kcssyttcaOWWAt/OdMubfI53fVBDf3W4rnitaXRfzUG9Y0E7D87LdaUbYYtnILYapc6o4ZvNO3a0SDLG1LZrVrYkiePVY/qTsPIZBgsUxmUpVrUUu2RnpbLXORGenYGenZ79Ddnl4rYUE=,iv:nUdoJhO9Sac8cHaRD/0o1q6ogZLV6wNqA/F/fO6dEds=,tag:Rn0NxPpNoAx0Rj9wYqhrVQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
