apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:BbuI31bxnFdll2BnXlkeLqDv7kziAw==,iv:v8oew44xjQ097R4H81Iajkog/ylY6n5nZVtbe6zKatU=,tag:wYDy8KXj5Qyw3tKzB6cZrQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:SJol6xz0IYMUE14DN7aPUtMDvNQEQV0M3FgG,iv:qRkYbCy8lFqNEaDnLa0yQ6bRgpXKhbmLHSg2olD/VZk=,tag:p7ULdURWR7szPhNrSnIPXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeFZYNVcwV2kvdDdzcExG
        NHBnMGE5Nm5kZldRWmRiYlBJSXdXYzJYS1hvCk9kRTRBb0NwcVRXNjVPZ1ZuWk1L
        dUtXemRjS0dYTjdsekZjK3BydzdDU3MKLS0tIGMyc1hOajBNNWtHRHhLZjJYeTAv
        THdobmVCQWhVdzVFNVZlcjBEbVludUUKrDynvaG/ME/iYCC7RzSgN19v6Xrmvq5d
        szl0VM1D7d1TI8QrbE1/CxpVpMNK6VaXMYeFcbZfu4FVvEiKz0abCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T15:17:34Z"
  mac: ENC[AES256_GCM,data:6jKubTLQtYoZv7svfinhRXYP9pt8zvcABFQGQCNAUGonEKMXK2V02M4XmoEFgMlve1VKBN33l9d8KX2RTr+9IBmGRWQQREnYclvlCpc9HUCVVGYKy8jK7CitHjGq3DDeOmy9Kc6/ORxL0fmC+3gCdza0x/cA2vwIAeLJecmwCQQ=,iv:4dGcTQNZcvtKgQ4yf3wtiujy2x1NdaYmuS2VC+tqdpU=,tag:bP0wxkGjFTNm7PiWpS+twg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
