apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:wWrr+vG+ukudSOZemTKzSpv3ro23pw==,iv:lLs6YPzm9EUQue8LQNspqxY6gTNZVpmO1Ra5Nx+WWWY=,tag:4hLqECO4qIiwPbofse4hIA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:Z5NFvDft9mmRdsO/IJMD+t3LMtDfgfn54ccjdQ==,iv:4u7mxjkMFsF6o974V/IWPa/xnBI5RpnoUbHCN7vO3z4=,tag:UD0njlHRhjE+weGCqWlxVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOW1oaVAyMkRhMlRmV3dy
        U3pRRFVleDEwcVZQeTFHM2lMSjBtd29rSEZvCjNEMmZsaWkwRUwzeUZrVEw5M2Jo
        c0pGKy8va3BuMTdCcDdHRERRaUhSNzgKLS0tIEk0QmZ2dzFOVUJDcGU2NlJqWnhs
        ajN0citRdExvclQ3K0ljMTg4bU5XNjAKNyQZGKCYrO8e0SpyIbXn+/bnlBnGNSgB
        lW7GJOWbCpv+9gIOMuGel5E0T3i1Sz+Zg3dvINRQkYCmS8O9HtGSvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T15:33:05Z"
  mac: ENC[AES256_GCM,data:EaHhvSxX8MSdhcZ6stgjJ7e2BHUbltQlPmCplOWEJccO79aeH4WD+7UxpBhrIOHcys/kkcLCT6VA7plk/Rh397V5jYtwkZceaVtgwaOhTwbFPLxDfyPdvm0psVcalXbrT+RAYwkfX5v5cC3Bm4DUu2bgo2hhQecQr1LyLPUoAYs=,iv:lW0bsyYCcj756PzvbVZWII6UNZlVOKYW6hk0dtY5bA4=,tag:oVL5N+dPek9JwT5+XQ2uVQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
