apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:iDO+EwbFcr25badK8I7MysjiFcc6AQ==,iv:z8HNX0+cDo7OlOTtdOyOP01gDzHCKIO8ZpcXOJA9T4g=,tag:FFx1+hrA6SWhxt7qryI20A==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:0WdKjYlfXNMrR+Zx6z638les3s6jBV2BNPsr,iv:HYmN1PSWPELdcepyR/4MuDSbupxbG4TtY+cvMLIALFo=,tag:EG/8XKSiyqHvJGzHJ9Yg0Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aGEzZGZNZ1R0ZXpxVGQx
        SDhXU3BkZTNVdFBLampLMnJHTjhTeDdpeG1VCk0zZnlkY0ZxbldhZVBLWWIxekp5
        d1V5SStMTEpEV0EvbFUzUDZOTjZKeVUKLS0tIHlncDJFSGVtL2UxdUlNL1Erdmpq
        aEVRbjJ5a1hQMUxqcW1PYzVVMGx6T00KrQ4e4LC6C17OK1kYEZKCThSONJCdxHou
        x7LBkAbgseeT4uKSGBSxzNqc5/2aULB/O/748s5VbKfsUjut2m1EgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T12:53:31Z"
  mac: ENC[AES256_GCM,data:v46dLeo/U6OSHHxaviLOpSZ4UrcsI16cm3crUnp93T0V/Ky+3cGx9UO5p7r4lk4Ak8BDeoG9YVeCmRjPYPNXWMHyalwgT78xG5g7kRk111tklUaX2ciXAUZCTe4MmMs+b0IIGVZkI3dfSD0c7t0vFmiY4ahRdf5Id1uKX1Fbvaw=,iv:r+37oF6KQeWWZaOCMwQylP1HlLUoszHOOZxy2f6TL88=,tag:IB5RQrwahhBCdAsSxx5xIA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
