---
machine:
  type: controlplane
  ca:
    crt: ${MACHINE_CA_CRT}
    key: ${MACHINE_CA_KEY}
cluster:
  ca:
    crt: ${CLUSTER_CA_CRT}
    key: ${CLUSTER_CA_KEY}
  aggregatorCA:
    crt: ${CLUSTER_AGGREGATOR_CA_CRT}
    key: ${CLUSTER_AGGREGATOR_CA_KEY}
  etcd:
    advertisedSubnets:
      - 10.0.10.0/24
    ca:
      crt: ${CLUSTER_ETCD_CA_CRT}
      key: ${CLUSTER_ETCD_CA_KEY}
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
  serviceAccount:
    key: ${CLUSTER_SERVICEACCOUNT_KEY}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  node-role.kubernetes.io/control-plane: ""
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeAPIServerConfig
image: registry.k8s.io/kube-apiserver:${KUBERNETES_VERSION}
certExtraSANs:
  - 127.0.0.1
  - 10.0.10.245
extraArgs:
  enable-aggregator-routing: "true"
  feature-gates: ImageVolume=true,MutatingAdmissionPolicy=true
  runtime-config: admissionregistration.k8s.io/v1beta1=true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeAuditPolicyConfig
configuration:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
    - level: Metadata
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  anonymous:
    conditions:
      - path: /livez
      - path: /readyz
      - path: /healthz
    enabled: true
  jwt: []
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeAuthorizerConfig
name: node
type: Node
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeAuthorizerConfig
name: rbac
type: RBAC
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
extraArgs:
  bind-address: 0.0.0.0
image: registry.k8s.io/kube-controller-manager:${KUBERNETES_VERSION}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeEtcdEncryptionConfig
config:
  resources:
    - providers:
        - secretbox:
            keys:
              - name: key2
                secret: ${CLUSTER_SECRETBOX_ENCRYPTION_SECRET}
        - identity: {}
      resources:
        - secrets
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
image: registry.k8s.io/kube-proxy:${KUBERNETES_VERSION}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeSchedulerConfig
extraArgs:
  bind-address: 0.0.0.0
image: registry.k8s.io/kube-scheduler:${KUBERNETES_VERSION}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.0/website/content/v1.14/schemas/config.schema.json
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:admin
allowedKubernetesNamespaces:
  - system-upgrade
