# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.8.2
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.31.2

clusterName: "homelab"
endpoint: https://10.0.10.245:6443
clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"
additionalApiServerCertSans: &sans
  - "10.0.10.245"
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "nas-vm"
    ipAddress: "10.0.10.249"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:a0:98:20:7c:e9"
        dhcp: false
        addresses:
          - "10.0.10.249/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "10.0.10.1"
        mtu: 1500
        vip:
          ip: "10.0.10.245"
  - hostname: "pve-vm-nvidia"
    ipAddress: "10.0.10.250"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/a31d81eceab05afdc2c59b0002701173e117a5fb81bdc1f64062d27655145848
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:bc:93:38"
        dhcp: false
        addresses:
          - "10.0.10.250/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "10.0.10.1"
        mtu: 1500
    patches:
      - "@./patches/pve-vm-nvidia/nvidia.yaml"
  - hostname: "pve-vm-2"
    ipAddress: "10.0.10.251"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:0b:72:b3"
        dhcp: false
        addresses:
          - "10.0.10.251/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "10.0.10.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/cluster-discovery.yaml"
  - "@./patches/global/containerd.yaml"
  - "@./patches/global/disable-search-domain.yaml"
  - "@./patches/global/hostdns.yaml"
  - "@./patches/global/kubelet.yaml"
  - "@./patches/global/openebs-local.yaml"
  - "@./patches/global/csi-local.yaml"
  - "@./patches/global/sysctl.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/api-access.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/disable-admission-controller.yaml"
    - "@./patches/controller/etcd.yaml"
    - "@./patches/controller/mayastor-patch-cp.yaml"

