# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.32.2

clusterName: "homelab"
endpoint: https://10.0.10.245:6443
clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"

additionalApiServerCertSans: &sans
  - 127.0.0.1
  - "10.0.10.245"
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "nas-vm"
    ipAddress: "10.0.10.249"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:a0:98:20:7c:e9"
        dhcp: false
        addresses:
          - "10.0.10.249/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "10.0.10.1"
        mtu: 1500
        vip:
          ip: "10.0.10.245"
  - hostname: "ser8-1"
    ipAddress: "10.0.10.252"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/aeec243e3a4c2a14f9ba74b1a8c7662f03eea658a7ea5f1c26fdd491280c88f8
    nodeLabels:
      feature.node.kubernetes.io/amd-gpu: "true"
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:75:6d:41"
        dhcp: false
        addresses:
          - "10.0.10.252/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "10.0.10.1"
        mtu: 1500
      - interface: br0
        bridge:
          stp:
            enabled: true
          interfaces:
            - enp6s18
          vlan:
            vlanFiltering: true
        mtu: 1500
  - hostname: "ser8b"
    ipAddress: "10.0.10.251"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/aeec243e3a4c2a14f9ba74b1a8c7662f03eea658a7ea5f1c26fdd491280c88f8
    nodeLabels:
      feature.node.kubernetes.io/amd-gpu: "true"
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b1:9e:54"
        dhcp: false
        addresses:
          - "10.0.10.251/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "10.0.10.1"
        mtu: 1500
      - interface: br0
        bridge:
          stp:
            enabled: true
          interfaces:
            - enp6s18
          vlan:
            vlanFiltering: true
        mtu: 1500
  - hostname: "ser8c"
    ipAddress: "10.0.10.250"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/aeec243e3a4c2a14f9ba74b1a8c7662f03eea658a7ea5f1c26fdd491280c88f8
    nodeLabels:
      feature.node.kubernetes.io/amd-gpu: "true"
    controlPlane: false
    networkInterfaces:
      - interface: br0
        mtu: 1500
        dhcp: false
        addresses:
          - "10.0.10.250/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "10.0.10.1"
        bridge:
          interfaces:
           - enp6s18
          stp:
            enabled: false
          vlan:
            vlanFiltering: true



patches:
  - "@./patches/global/machine-features.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-udev.yaml"
  - "@./patches/global/openebs-local.yaml"
# Global patches
# patches:
#   - "@./patches/global/cluster-discovery.yaml"
#   - "@./patches/global/containerd.yaml"
#   - "@./patches/global/disable-search-domain.yaml"
#   - "@./patches/global/hostdns.yaml"
#   - "@./patches/global/kubelet.yaml"
#   - "@./patches/global/openebs-local.yaml"
#   - "@./patches/global/csi-local.yaml"
#   - "@./patches/global/sysctl.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/api-access.yaml"

# Controller patches
# controlPlane:
#   patches:
#     - "@./patches/controller/api-access.yaml"
#     - "@./patches/controller/cluster.yaml"
#     - "@./patches/controller/admission-controller-patch.yaml"
#     - "@./patches/controller/etcd.yaml"
#     - "@./patches/controller/mayastor-patch-cp.yaml"
#
