---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # dependsOn:
  #   - name: rook-ceph-cluster
  #     namespace: rook-ceph
  values:
    controllers:
      radarr:
        # annotations:
        #   reloader.stakater.com/auto: "true"
        initContainers:
          filesync:
            image:
              repository: alpine
              tag: latest
            securityContext:
              allowPrivilegeEscalation: true
              runAsUser: 0
            command:
              - 'sh'
              - '-c'
              - |
                apk add rsync
                echo "Staring copy"
                rsync -avPh /mnt/original/ /config/
                rsync -avPh /mnt/originalCache/ /config/MediaCover/
                echo "Finished copy"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/radarr-develop
              tag: 5.20.0.9752@sha256:b19e4d4dca881fe36718d1f4139b3376bf8ddfc4eb31b96857f4378a86bc16c1
            env:
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__DBENABLED: "False"
              RADARR__LOG__LEVEL: info
              RADARR__SERVER__PORT: &port 80
              RADARR__UPDATE__BRANCH: develop
              TZ: America/New_York
            # envFrom:
            #   - secretRef:
            #       name: radarr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: radarr
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      original:
        existingClaim: radarr
        globalMounts:
          - path: "/mnt/original"
      config:
        existingClaim: radarr-config
      originalCache:
        existingClaim: radarr-cache
        globalMounts:
          - path: "/mnt/originalCache"
      cache:
        existingClaim: radarr-cache-config
        globalMounts:
          - path: /config/MediaCover
      # scripts:
      #   type: configMap
      #   name: radarr-configmap
      #   defaultMode: 0775
      #   globalMounts:
      #     - path: /scripts/pushover-notifier.sh
      #       subPath: pushover-notifier.sh
      #       readOnly: true
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: 10.0.10.3
        path: /mnt/storage/k8s/media
        globalMounts:
          - path: /media

