# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
stringData:
  client-id: ENC[AES256_GCM,data:FRRoj3GvHSOkXaK3K/Rirjg=,iv:BbHU+ZvA8AyoZV6nGw0QHclq8vRkXpOYC0RJZ82J/Iw=,tag:lvx4yW2alDsHjK3ch13Jqw==,type:str]
  client-secret: ENC[AES256_GCM,data:dit0qRavtrT2/IOKBTF4a1l3ZuEW0RdZpqfq8FEFszouNXb27ZOfEljK2QhBb7kBtVRwBSmz8bhfV51B7nyu,iv:K1YfOzt/tRqagUFhkCB3ocsZcZ2M+4T0K7463/p17Qs=,tag:muqyVN2u/M1BkIu+pkdVxw==,type:str]
sops:
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRG84OHlEdUdBOFVPeHls
        b1RWTXpNb01iMnB3OEpRbUFlRkhzZy9HbkZ3Cm5UN1VpV20xaThvWmF1a1B0eWln
        ZWhVNnBSR3ovTHhJR2w0Um8zUkpvR0kKLS0tIFphVzFHOHhyTHNjMGhhem45SlF5
        cERBaTVEL2NNWFJNcXlKT2xpUEdwOGcK++3yuWEUk1/g3G6LTuKi+Y1mPQwnWT5s
        oSMn2kz5xzH18mltUToMBpZWogi6ozuQFZMoJbaq3jvU2AcP01Jg3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T20:22:06Z"
  mac: ENC[AES256_GCM,data:1385e06MY6RdFA94rBbSXggXX6l6gXLqeqAlhuR8N2TzOn8TIpXef0i4YdCdi0S97XId6+Ij+l1PAa2uGGva5iDCv4J94t03D/N290vl5s9GeCLQiVtyNn8ZXEFbx/GwvF0m2lnUBoCZOXOplkbU9bQL3HjzyejR9G471vQgtxg=,iv:Tu1zwiJ+BjDoW6F5+qdlmjoyHo5zf5toXn/XSWOjCyU=,tag:S1xbooEa+cESZHCKCjYrdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
