apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:G7C+fkHM2c0JRR6QLKE=,iv:BVYanfq0/LQAHkVVqsUINDgM2ZTCvHFECvpfgnOAZ4U=,tag:Og2iORmnLEzvHifWs9yX2A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:M+kArA+TwSYESzvPwZ2j3wtCfo9L,iv:3KeDGLGaZrDIW4t4eqdlbVnJCzqO7uIqTIMOBqrxghs=,tag:QZNsg5VEMfA7A6MXup0rVg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PORQKGrmdbv0go5WL9ZVojYTC+qZMUGmiwEb/64wn9WF25t6,iv:ezBrCkwwrJdFbUy3sSBzzQv5MArKfdcEIlzfF63H3fQ=,tag:1CHxBp67oQpTWz6C5IxVwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTHdIZEl0YnJSUjhzQkxC
            VjhMMkF6dzdadE1leU45TzNMdGlERzM2Tm5rCnNEZVZiMTI3bFVkV0ZCaWxjVHIr
            Qllvb3NrcmozQytGcDV6cHp3UHZiUkEKLS0tIEFsRTBzQmxpT2gxT2xIenlCcUk3
            QVNQTW1WdmMxbWgyRGNpSEhucWgremMKFQSH/zaSgcTKWYMB5sT0e/W6KHPY8VZ4
            fO+DGTbSK/b9guAUd0+jrvJjY5LaJxRDjTLcmDL6BbHWle/j3K25zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T19:30:35Z"
    mac: ENC[AES256_GCM,data:EUushb0D98mVditvXpBxKmiydH7YMaABJ1rLL5Ogav00IYnzSR6Ujnlzzab7Ec5hDu3vVzVEu/KXFi83h1HXkaKWh0Vag+fWdtAbIMb4JvlZ2oeej0qgqrtQ9u47J72zkSs6ArS2xwdZ6rdHZyxOGSop/JdXetXrvzvx6dfokEI=,iv:czQS8UbxNSm86HrPDybk9JvGC9MzlVnDA7ki0m0NIQY=,tag:bxX01QsqdTxhbvC878V6OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
