apiVersion: apps/v1
kind: Deployment
metadata:
  name: omada-controller
  namespace: omada
  labels:
    app: omada-controller
spec:
  selector:
    matchLabels:
      app: omada-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omada-controller
      annotations:
        k8s.v1.cni.cncf.io/networks: default/home-macvlan
    spec:
      initContainers:
        - name: fixroutes
          image: nicolaka/netshoot:v0.13
          imagePullPolicy: IfNotPresent
          env:
          - name: DEV
            value: eth0
          command:
            - '/bin/bash'
            - '-c'
            - |
              echo -e "\nip route before fix:" && ip route
              POD_IP=$( ip route | grep $DEV | grep default | tr -s ' ' | cut -d ' ' -f 3) && \
              ip route del default via $POD_IP
              ip route add 10.69.0.0/16 via $POD_IP dev $DEV && \
              ip route add 10.96.0.0/16 via $POD_IP dev $DEV && \
              echo -e "\nip route after fix:" && ip route
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
      containers:
        - name: omada-controller
          image: mbentley/omada-controller:5.15
          imagePullPolicy: IfNotPresent
          env:
            - name: "TZ"
              value: "America/New_York"
          ports:
            - name: manage-http
              containerPort: 8088
              protocol: TCP
            - name: manage-https
              containerPort: 8043
              protocol: TCP
            - name: portal-https
              containerPort: 8843
            - name: app-discovery
              containerPort: 27001
              protocol: UDP
            - name: discovery
              containerPort: 29810
              protocol: UDP
            - name: manager-v1
              containerPort: 29811
              protocol: TCP
            - name: adopt-v1
              containerPort: 29812
              protocol: TCP
            - name: upgrade-v1
              containerPort: 29813
              protocol: TCP
            - name: manager-v2
              containerPort: 29814
              protocol: TCP
            - name: transfer-v2
              containerPort: 29815
              protocol: TCP
            - name: rtty
              containerPort: 29816
              protocol: TCP
          volumeMounts:
            - name: omada-controller-data
              mountPath: /opt/tplink/EAPController/data
      volumes:
        - name: omada-controller-data
          persistentVolumeClaim:
            claimName: omada-claim
