---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: omada-claim
  namespace: omada
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
