kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: omada-controller-claim
  namespace: omada
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
