---
apiVersion: batch/v1
kind: Job
metadata:
  name: kopia-init
  namespace: volsync-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: ghcr.io/home-operations/kopia:0.23.0@sha256:76865b421548b1d7bb26a8268f0f0bc828be4eec3f8d8b9c8ece991c99878f94
          command:
            - kopia
            - repository
            - create
            - filesystem
            - --config-file=/config/repository.config
            - --path=/repository
          envFrom:
            - secretRef:
                name: kopia-secret
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: repository
              mountPath: /repository
      volumes:
        - name: config
          configMap:
            name: kopia
        - name: repository
          nfs:
            server: 10.0.10.3
            path: /mnt/storage/k8s/kopia
