apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:QsNmpPu9KA1dQgjOleK5VyXi0Tucfw==,iv:np7i++JSYGnMdJ22EJd9yxPWhm9oG8EndWsIQSwAlwY=,tag:RWk59UrlZymL5UqYHQNCcg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMWM3Mm4rRjJmQmtvRlg5
        TFNJNFQvUmlZOVNCZFRxcVJscU9qZnU4RlhJCjJ1UFlPNTRxMzd0TFM5Y01sdC9u
        SXdMZlR6WlE5RnU5d0pvdUpVNHIycG8KLS0tIFJIeGs4akEzZUdOMXRNeHBSb1hw
        dUxUNXhOVURLN3gzSWFkSHo4MC85VkkKHu3q5QGyNYVlFNhXtIT3/JAnbdr6pYXL
        LGefEpCHE+ps/0E/wZDtK6M4gbCkYfPn5YHMsr6h3HMu0TgxKvGs9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T12:53:31Z"
  mac: ENC[AES256_GCM,data:/5xkxm0RDX/qsLbfpcCGEQhlIsVVsGnxKewlnumLw55ko7EZtDNghPjBmg1KbmdyRSO8qsnDKCIqXoZAyJJTdbGZt2+T+KxVkZHPQDioEKMhOyB3g7bKJClc73Q1GFsq5mIrRLfgYtZy0588EedQuW7dRzr+Dzz2aCo/VDqDmN8=,iv:DDxV3YEEdrej0DtPKs3f7e94/3TOuLM4GdwiwHuALMU=,tag:AA4T8orJAqgH7dHarWfM2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
