apiVersion: v1
kind: Secret
metadata:
  name: omada-exporter-credentials
type: Opaque
stringData:
  OMADA_USER: ENC[AES256_GCM,data:NlTeVQsNcg==,iv:eGITQhQeKqK/YtqUL6xGw4gE5DAOoBp5uTPA4U15UJc=,tag:LMXibfOvIutEVFv7Ub+zYA==,type:str]
  OMADA_PASS: ENC[AES256_GCM,data:D1OZnzNmeKkQUlNVfoLTK3L67JcoBNLV,iv:z6S1WDLn6PmK1nQcdIRIf/BEGBfRgb0XgUjsSexAewY=,tag:ed3LzKbdJLuulR60MHvWwg==,type:str]
  OMADA_CLIENT_ID: ENC[AES256_GCM,data:kW3c0WYksK2Vu8ADgKZ3WjHxc7M5/wv2oDVXF162w5k=,iv:hhtIqXymMyJv2oitRKSahDMP7vs7Rot5Kd+mwHG9RFY=,tag:cbqT0y3jSX22w/R/3cXGrA==,type:str]
  OMADA_SECRET_ID: ENC[AES256_GCM,data:c8the/3cig4VlnuPZAc0V0jiZ6Z2Rv3iQiCgA+6mDHc=,iv:BJxvVJuvBNvYLVMY4zcwnhj2EF2Z44MmNxuhcaf5UvI=,tag:bOUU4KUFIXiToZJSOyUMOg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYTU0VE5BVFFnZlVGcElC
        VnN1UHJRRnJ6QmV4VDQrYjhFZEdlYkNGMDJZCmQ1dWtTU2lqYWtKOUlwdWZTWlFK
        TkxKWUdBRkZHb3lTSW5sVzVEMSswZHMKLS0tIGRnTW1hc3JjeVQxbDBhUW1kbm5W
        RUZHVUE2MzlGS2hidVB3QlYxUVYyVEkKe7U6xsO+jSWcr4WQB3AMqF1cSceLTdCI
        J62OnOo9i+3oRZO1KsKchPxNCIV+0YXp2FbEBZ5oTR9X32n6sZndAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T17:55:14Z"
  mac: ENC[AES256_GCM,data:Wkn7szbevlh0XnphuPoSIw88RDBh24YFVHBY2GMLOehRV6RI33kV1MbWbfdoyxu+le/FBtP6/Z0JxbS9vWPymB5YbJf5kaAqf5qxPWpmGVsFpClZ5E9/1DB6oP7CRKFshs17CKD1dkQ4mEUU4JetM6rtgVNQjF+cOU5aL+dj3wg=,iv:ooYS3AJmRXAtpH5L5oP5Dgxuu7KX5RYnwJGN+Y6Yafc=,tag:L6ZURjOkHSaxHbRM8CrRBg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
