apiVersion: v1
kind: Secret
metadata:
  name: omada-exporter-credentials
type: Opaque
stringData:
  OMADA_USER: ENC[AES256_GCM,data:NlTeVQsNcg==,iv:eGITQhQeKqK/YtqUL6xGw4gE5DAOoBp5uTPA4U15UJc=,tag:LMXibfOvIutEVFv7Ub+zYA==,type:str]
  OMADA_PASS: ENC[AES256_GCM,data:D1OZnzNmeKkQUlNVfoLTK3L67JcoBNLV,iv:z6S1WDLn6PmK1nQcdIRIf/BEGBfRgb0XgUjsSexAewY=,tag:ed3LzKbdJLuulR60MHvWwg==,type:str]
  OMADA_CLIENT_ID: ENC[AES256_GCM,data:kW3c0WYksK2Vu8ADgKZ3WjHxc7M5/wv2oDVXF162w5k=,iv:hhtIqXymMyJv2oitRKSahDMP7vs7Rot5Kd+mwHG9RFY=,tag:cbqT0y3jSX22w/R/3cXGrA==,type:str]
  OMADA_CLIENT_SECRET: ENC[AES256_GCM,data:ZvxvBxf5eb+UHelC0xbVKuwe8zsmIGWtCx8uQ26nH1Q=,iv:PZpTFCrk+Y+N4BbQ5PpjXgKd9SHvdVGQCRHizTmY8Ms=,tag:sb9AKuFF7kZV+5gC65+4kw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYTU0VE5BVFFnZlVGcElC
        VnN1UHJRRnJ6QmV4VDQrYjhFZEdlYkNGMDJZCmQ1dWtTU2lqYWtKOUlwdWZTWlFK
        TkxKWUdBRkZHb3lTSW5sVzVEMSswZHMKLS0tIGRnTW1hc3JjeVQxbDBhUW1kbm5W
        RUZHVUE2MzlGS2hidVB3QlYxUVYyVEkKe7U6xsO+jSWcr4WQB3AMqF1cSceLTdCI
        J62OnOo9i+3oRZO1KsKchPxNCIV+0YXp2FbEBZ5oTR9X32n6sZndAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T17:53:34Z"
  mac: ENC[AES256_GCM,data:NpEk6ujAennWLl4sWkHt7fIm8x80jrZ4rDVcZGWJ+KayYFappKyhVRxX5kTsN0ls/Yx6gmB3L7Cdpf8A6rBRrFT8q+OVNnzA2P2/ofneJApdriwlpEhL9nG1rJgGPxkc7Y4+u/8JewwDjyEXTk7WbWTmN7Hq9jZZtV1yTfPgJiM=,iv:jxTcfzE1M1nPKQdlB/FSxKAKh0bxrolJT8SfsxneuYU=,tag:1iWZcUdFONsEyOpBV46tmQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
