apiVersion: v1
kind: Secret
metadata:
  name: omada-exporter-credentials
type: Opaque
stringData:
  OMADA_USER: ENC[AES256_GCM,data:EH6xl0OPGfg=,iv:K7Bb7NfJjbdAE0EndYxQL10WGI1xsdBWBU7Mq9A2zvs=,tag:FDFQlAhdjvY/RgqHQg5iWw==,type:str]
  OMADA_PASS: ENC[AES256_GCM,data:eIOse04K6fU=,iv:cC7ppduQVxTN8bOcmMCIfKFpMQTHwf3NMjTe6eXqNWA=,tag:CYpBgXq4mI3UeKWXSO7qQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYTU0VE5BVFFnZlVGcElC
        VnN1UHJRRnJ6QmV4VDQrYjhFZEdlYkNGMDJZCmQ1dWtTU2lqYWtKOUlwdWZTWlFK
        TkxKWUdBRkZHb3lTSW5sVzVEMSswZHMKLS0tIGRnTW1hc3JjeVQxbDBhUW1kbm5W
        RUZHVUE2MzlGS2hidVB3QlYxUVYyVEkKe7U6xsO+jSWcr4WQB3AMqF1cSceLTdCI
        J62OnOo9i+3oRZO1KsKchPxNCIV+0YXp2FbEBZ5oTR9X32n6sZndAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T17:47:03Z"
  mac: ENC[AES256_GCM,data:Df9LOpuaFy6OmepfhLBxQ7Xrp5KUc+au+4NTfKESdtzVluls+o0Gyq/dJ65RSF//lt6U+13+WuDhqu2CcNVdC+HVki2Y6nbVdMLlCuNWTpLiQFtHom6bwZv3eaZSqp/kREzM/Mku8VGpYLmPpzXwtoIC59+loSIA/HbrMw7ksmY=,iv:7O4IuaHcqYM2TwI/v8Cw30AyXwQUOqiPqVoiCd4N2D0=,tag:5mQniApmpVmc6UvGSCFAWw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
