---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: "node-exporter"
spec:
  staticConfigs:
    - targets:
        - localhost:9100
  metricRelabelings:
    - action: keep
      regex: (node|process)_.*
      sourceLabels:
        - __name__
  relabelings:
    - action: replace
      targetLabel: job
      replacement: node-exporter
