apiVersion: v1
kind: Secret
metadata:
  name: victoria-metrics-secret
type: Opaque
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:lWOPFdEEfdFL2kdcKrYbLKRYFpifs2mGL3AXAuEH,iv:P3KWL2aYcFuzguC+nXE1Q46pRaqryDZJo/ACqRxlZqA=,tag:hD94DDjCxHQ6FlAK9jP+Mg==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:3nSL7H0l7hYrp3OG1cFNaAUt8EOpR9qUhqp0F98p,iv:WMymcQEbugAXQXO00Dg6sxfH2MVCHG8KvHGpnsXcG5E=,tag:QEWi832N/olWbF1+xAgbWA==,type:str]
sops:
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZGNXQXlCSmVRUmpXd1l0
        TDVNVkxiN3ZPdzdzNmdRSGZzVy8raEgwUWpFCmZlWmJNV3lQb0ZUTDZmZ1FuYThV
        dEdPWkx1clNQRkZnMHhpNktzdWRkSEUKLS0tIGUvYXN3cm5Pb1h3b0t2TmNncE80
        UjQ4NTFocEcxYTg1bHArYkE0di93WDQK35eCBRfS4NXnWXnobm9aUoxF9MlFMJob
        tEuiP5/F51b7hm1smURhkF/oKOLyfiUqqBkFlu+TBE0cO6C+jFJtLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T16:54:08Z"
  mac: ENC[AES256_GCM,data:EUeDZHWMZAXggvejjqg724ZuB4dH3+c4T2v8SEvxhVnhG5Vj1uLmcWP+WzFGRIG6W36Cao48FxJuN3bG4ziHjxaGGRs8Pe/6hglIfqvj1HpMlfr/isvMuWsM51b1FrG070m1fuOWiBT+9/517dY2l5B1fpaPyylpIC5R4vtuRJ8=,iv:x+iaj2y+DTObBywDxdFXoudBQmx7eykthAjtz6AhCTg=,tag:KgDC1GEvLQY89RwagMIo/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
