apiVersion: v1
kind: Secret
metadata:
  name: victoria-metrics-secret
type: Opaque
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: "abgwguxm4dnu7rws7iepfbrk77sb8m"
  PUSHOVER_USER_KEY: "uaunmmu9dvcfvuf9jcztuy2r1wqbpf"
