---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app multus-cni
  namespace: &namespace kube-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/kube-system/multus-cni/app
  prune: false # never should be deleted
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/resources/limits/memory
          value: 500Mi
        - op: replace
          path: /spec/template/spec/initContainers/0/command
          value:
            - cp
            - -f
            - /usr/src/multus-cni/bin/multus-shim
            - /host/opt/cni/bin/multus-shim
        - op: add
          path: /spec/template/spec/initContainers/-
          value:
            name: install-cni
            image: ghcr.io/siderolabs/install-cni:v1.9.0
            command:
              - /install-cni.sh
            securityContext:
              privileged: true
            volumeMounts:
              - mountPath: /host/opt/cni/bin
                mountPropagation: Bidirectional
                name: cnibin
        - op: replace
          path: /spec/template/spec/volumes/8
          value:
            # brittle, consider another alternative
            hostPath:
              path: /var/run/netns
            name: host-run-netns
      target:
        kind: DaemonSet
        name: kube-multus-ds
