apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Qfv7Tep5PSztprQBzaxoZyru,iv:x+2GgC4AY5skcvWG8faOqU0Sh4+E+uDROeFvNZmHUMU=,tag:oVNC22gTTukR93KYp6XRGw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUVpTNXE2NFM4ZUhYWUti
        dWk5RGVxeldFb042L3grdzRTQko0NHN2OEV3Cnc4bGFqdGpCdS9YYWVWOFVEd0F3
        OVNib3d1RWNTV2sxTktFSldXMjBmcmsKLS0tIEQ2eWJ1M1orMXluU3cvRmJQS2Vj
        cy9zOEtKOVNQWDd6MktaeVZFSTBLaXMKQcfRrgjWRosoCzWw5XJaev1TA72ua23u
        hYpc3ikmr917uEDFkqEjwJ1wSBMHLURT9A72D9oAT58rdA5OrX0Izg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-15T16:38:29Z"
  mac: ENC[AES256_GCM,data:wtoGXYA8cHw7GuZfy/tFofD94SRqGxyczROk0K//8amaWh2ZNl+fsph1q8+uIvUS1x9Nmtk6dFChSyFdlckdgVztextJyLkvByfVcAbQl5+pcubKnLkCqw4Vj2zlTltVyeagRFJMod0z097FmZD9DTJFA+ZbCvmHjUPoNJ9pzbc=,iv:g+sRb1L6SX+t6uICP5hKQELyKQxabwaS6uCRdKj+W0E=,tag:/BM+6CLMSZQs3jfKZ5SrsQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
