apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
  namespace: rook-ceph
type: Opaque
data:
  password: ENC[AES256_GCM,data:hO3zZj4bD2UKTXZHkmb0m9C0,iv:PoEoeQ6lk7YTsocdR6pTPRmo29weCOJR8vW+uSNavn4=,tag:eU2r22/2xnADlgtsvsEO6A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5clBmeUltWGpkSUNHUUFM
        MVVXREZQM2VvRWRzdG1oMldxd2NMUTFvZGdnClFaZndnU3NhelRTZHM2dGRzdVBl
        SlBtYjBqRm9nd29GeG1iYWtxSVRWUDQKLS0tIG04WFNQWnJPYjNSQjFvV3d6OTZl
        ZENUQm1JM3QreFhHRnhzOU5lYm1MRXMKUMB+oninR2sFZUl97JXUNxYUJ4j6oAN3
        djFAbuaOEeea4FSwtQoFT/JX3pBIaaUstJFqbqdeJHY6krvZ8ESW0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-15T15:18:16Z"
  mac: ENC[AES256_GCM,data:EPld/Xlkex0oXYbVZwnApqKADxbk+Uic/BYyEFiAOrshKLiudY4piMlsht+gzijd8EDOFmaqmll5vW1UrQvsmwqlNL9WAVZE/bX8gg2RjjGRP7L5MSsnpXU46k0PFTuS0OIDJL/C4zch3gZjoXoqIxKCl3PxsGGFb016fHyzH9E=,iv:AnuyNV4ULnGVtMHQsDaJHyZxvpY8HRsXpvpSi0H05xY=,tag:d3NeUws0Jonvuyr9fcQnFQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
