apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:FwSuBBTai11h7Wl9HF4=,iv:r78pUZS9HK7Rb6ifvMBii9oGk0O9jhesnNM0guIlhgs=,tag:CYjOQemhvhGnaQkGKoJgUg==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:DGgNNIN51bXAU9qJO5Wl83zT3taX,iv:KIZtzLt69voxtqIn+bx5xqzDlB+R3ja6HkDTvlvvmJo=,tag:eed6bD6Dc04GPL3CZrI+rQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bJ/b/SwOVa6ZJV0ZR/CGf1lk072mG9uBR+cJXRmsgpCx9gHJ,iv:eZDygGyCdfSJ9HG7g8gLS7fe/N/i8Ipi5mgqr18o14I=,tag:0ZhpxXpZRlQ3x6Ge/YFCCw==,type:str]
sops:
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS0hMSXVCQy9aS1J3K3ZE
        ZnB6UVhnbVlldXNMdnBzdGRZTHZ4WHYyalR3ClpycHN1cFlGdWhQVFBWbXY3REti
        S25Ud3UwbUhPSEgycU9DWkJ2L0d5bzQKLS0tIFpmVnVtT1NNd005RTVTRExCQys2
        UWVXQ3g5TDUzcWFOT243Z2ltRkxRaFUKDCR4a2BH7gpf7n29rHfYEGsZvE7aL71y
        U8Z2fUfkISpRy+Bmt1qFVfW74hop66HviUvaw6B7cxQW1JS3lRTGQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-27T14:04:11Z"
  mac: ENC[AES256_GCM,data:Wso7JTK3ZLKrz32XsSn5EyhyOFYf5YEV+pqcQFj9VXlClW8k36SHVdwLyVQnlzQa5PRbvQTaDuLfZZ11jq96ATrK87Q02lDQhGetQuJe7yjECu6okdUzmH8w7c009OSRaIPwAputuNGuVZFecLM6pEsiGffkqs72IzuJRras4zw=,iv:BugV2A+K87fYtP/mAtM0/gIkVNu9qNDGXYqQH+Nt8L8=,tag:I7BHVvckT0UbHa4Lsvp8ag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
