apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:b/Qe1kiNh7IVpEIj0tRayxBcqKwbY0elUcemZNUJLQ7HfI8qsidCZw==,iv:AgwNHFeGzvyC1nQTz2HqD8oeLIFRuwrxxDlpUd7cJCE=,tag:PMsxOMQBsOqfmed4we7R9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUzNiVHdtOGhud0U5TGN4
            VEErMDEwaDNYaXduUEh4aGRYUEZMcnVSZ2swCnh1cE9qS3I2QjVocjhBUDJqZXlK
            V0NydmpnVkVtSSt4bkkvNHR3eU1LeGcKLS0tIEpZRGZMazZ4N3Yvb0VMME9XblJG
            bEtrTWNKUHNRT3U4MVRyUno5WkJBSWMKUZUBisyzd8lEJHZHLZzKJKL+fMPLELix
            U+gQb+E/QLeNHJ7hLxBLTDpSgaspCs9gTqBuHxjKLLIz4NPpogvKkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-22T15:04:02Z"
    mac: ENC[AES256_GCM,data:qTl4tg1TeDZURFW5pGijZlyD4F+ASfI1KnLWQ5Gd3Bw0lO2GGTaQc1Um1WbyWyYW3fUvl2K1ECnLQ2pY3FfyUv5ArHx2aGk38etlz8bf7StidbMmCmugQOn/Fhj9GcPQ9zArktjxmCChe5zOb8nHcnOKzYe6bdNYz8AFJ0I+XO8=,iv:a4p+GRZbrwNDmjVP6oTu33x13VwVOctdBU7bs5zxxIs=,tag:XaKWCoGx0ziy1MPgfBEJxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
