---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - tv_grab_epgshare=/usr/bin/tv_grab_epgshare
