---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs
  install:
    disableHooks: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableHooks: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    localpv-provisioner:
      localpv:
        image:
          registry: quay.io/
      helperPod:
        image:
          registry: quay.io/
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: /var/openebs/local
        reclaimPolicy: Delete
    # mayastor:
    #   csi:
    #     node:
    #       initContainers:
    #         enabled: false
