---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stunner-gateway-operator
  namespace: stunner
spec:
  interval: 30m
  chart:
    spec:
      chart: stunner-gateway-operator
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: stunner
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
